### ISSUE TITLE
Splitting the basic functions files into computation and visualization. 

### ISSUE THREAD

**Issue by ApurvShah007** [stocksmith/ml-research#12]
Split the collection of function into 2 files with more relevant names.

**Comment by Saakshaat** [comment]
@ApurvShah007 dividing packages is a good idea but I wonder if having visualizations is a good idea since our packages are meant to - return analysis on passed data.

**Comment by ApurvShah007** [comment]
Visualizing graphs is a big part of analyzing your stock data. Most of the times it's easier to plot the data rather than going through a dataframe. I feel like they are crucial class of functions that we should include plus they do not take much effort. 

I mean sure the user can manually plot the dataframes once we return it but I feel like we should have the functionality. Plus sometimes with the covariance plots and stuff, you don't usually want a dataframe in return, you just want to see the graphs. So thats my take. 

I will let you decide what needs to be done. @Saakshaat
